version: '3'

services:
  ri-synonym-web:
    build: .
    image: sdokara/ri-synonym-web:latest
    container_name: ri-synonym-web
    ports:
      - ${SERVICE_HTTP_PORT:-3000}:3000
    environment:
      - VUE_APP_SERVER_URI
    restart: ${DC_RESTART_POLICY:-unless-stopped}
